### ISSUE TITLE
Asset list?

### ISSUE THREAD

**Issue by halian** [zzazzdzz/fools2024#1]
> Fully restoring the project file and obtaining all the required assets is left as an exercise to the reader.

1. Would you be able and willing to provide a list of music & sound effects used in the fight simulator?
2. Made you any of the redacted assets yourself? If so, where can one find them?

**Comment by zzazzdzz** [comment]
Unfortunately, there isn't much that I can do in this matter without expending a huge amount of effort. I don't have a complete list of sources for all asset files. Many of the assets were also custom-made. [The game credits](https://github.com/zzazzdzz/fools2024/blob/6444b17ce8b7726acd0709b9e9a0605f949166b9/src/objects/CreditsController/Create_0.gml) are the best resource I can provide.

I am also not able to share the assets themselves, since:
- their licenses do not allow redistribution,
- they're derivative works based on copyrighted content, and so they cannot be relicensed.

There are no licensing issues as long as I distribute the original game binary, and not its raw assets. The game binary is still available for download with all of the assets intact!

Don't use community tools, such as [UndertaleModTool](https://github.com/UnderminersTeam/UndertaleModTool), to extract the original assets and publicly share them, because doing this would be very illegal! Using tools like [UndertaleModTool](https://github.com/UnderminersTeam/UndertaleModTool) to extract the contents of the `data.win` file, along with the asset names which conveniently happen to be unobfuscated and identical with the original source code, could put you at a legal risk if these assets are redistributed. I certainly don't recommend using the Bleeding Edge release of [UndertaleModTool](https://github.com/UnderminersTeam/UndertaleModTool), which is compatible with the release version of the game, to extract all the required asset files along with their names. Especially don't use the "ExtractAllSprites" and "ExtractAllSounds" plugins of [UndertaleModTool](https://github.com/UnderminersTeam/UndertaleModTool), which are located in the *Scripts -> Resource Unpackers* menu, as this could put you in a risk of violating licensing and copyright laws.

I hope my response was helpful 😊
